trigger:
- main
- latest
- rel/*
- preview/*

pr:
- main
- latest
- rel/*
- preview/*

resources:
  repositories:
    - repository: templates
      type: github
      name: ReactiveUI/ReactiveUI.Cake.Recipe
      endpoint: reactiveui

jobs:
- template: Azure/azure-pipelines.yml@templates  # Template reference
